version: "3.8"
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  php-apache:
    build:
      context: .
    container_name: "php-apache"
    depends_on:
      - "traefik"
      - "mysql"
    volumes:
      - "./www:/var/www/html/"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php-apache.rule=Host(`localhost`, `lvh.me`, `pmamp.lvh.me`, `127.0.0.1`)"
      - "traefik.http.routers.php-apache.entrypoints=web"

  mysql:
    image: "mysql"
    container_name: "mysql"
    depends_on:
      - "traefik"
    volumes:
      #- "./mysql_seed.sql:/docker-entrypoint-initdb.d/mysql_seed.sql"
      - "./dbdata:/var/lib/mysql"
    command: 
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "rootPASS"
      MYSQL_DATABASE: "dbase"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpass"
    labels:
      - "traefik.enable=false"

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: "pma"
    depends_on:
      - "mysql"
    links:
      - "mysql"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
      UPLOAD_LIMIT: "256M"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`pma.localhost`, `pma.lvh.me`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  default:
    name: "traefikNetwork"
